apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  namespace: default
  generateName: build-app-
spec:
  serviceAccountName: dockerhub-service
  taskRef:
    name:  build-app
  inputs:
    resources:
      - name: source
        resourceRef:
          name: git-source
    params:
      - name: contextDir
        value: .
      # Enable if you have maven mirrors to use
      # - name: mavenMirrorUrl
      #   value: http://nexus:8081/nexus/content/groups/public
  outputs:
    resources:
      - name: builtImage
        resourceRef:
          name: knative-tutorial-greeter-image

