apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: mvn
spec:
  workspaces:
    - name: maven-repo    #This workspace states that whenever this task is to run, a volume should be provided and mounted to act as the local Maven repository.
  inputs:
    params:
      - name: GOALS
        description: The Maven goals to run
        type: array
        default: ["package"]
    resources:
      - name: source
        type: git
  steps:
    - name: mvn
      image: gcr.io/cloud-builders/mvn
      workingDir: /workspace/source
      command: ["/usr/bin/mvn"]
      args:
        - -Dmaven.repo.local=$(workspaces.maven-repo.path)
        - "$(inputs.params.GOALS)"