---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-repo-pvc
spec:
  resources:
    requests:
      storage: 2Gi
  storageClassName: custom
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce