---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dockerhub-service
secrets:
  - name: dockercreds # Create secret for your container registry

---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/redhat-developer-demos/knative-tutorial.git
---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: knative-tutorial-greeter-image
spec:
  type: image
  params:
    - name: url
      value: vyomsoft/knative-tutorial-greeter
      # if you are on OpenShift uncomment the line below
      #value: "image-registry.openshift-image-registry.svc:5000/tutorial/helloworld"